### ISSUE TITLE
when using --dropout

### ISSUE THREAD

**Issue by pajkossy** [zseder/hunvec#35]
Traceback (most recent call last):
  File "hunvec/seqtag/trainer.py", line 123, in <module>
    main()
  File "hunvec/seqtag/trainer.py", line 119, in main
    wt.train()
  File "/home/pajkossy/git/hunvec/hunvec/seqtag/sequence_tagger.py", line 157, in train
    self.algorithm.train(dataset=self.dataset['train'])
  File "/home/pajkossy/pylearn2/pylearn2/training_algorithms/sgd.py", line 453, in train
    self.sgd_update(*batch)
  File "/home/pajkossy/theano/theano_env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 588, in __call__
    self.fn.thunks[self.fn.position_of_error])
  File "/home/pajkossy/theano/theano_env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 579, in __call__
    outputs = self.fn()
IndexError: index 9360 is out of bounds for size 9354
Apply node that caused the error: AdvancedSubtensor1(feats_W, Elemwise{Cast{int64}}.0)
Inputs shapes: [(9354, 100), (168,)]
Inputs strides: [(400, 4), (8,)]
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector)]
Use the Theano flag 'exception_verbosity=high' for a debugprint of this apply node.

**Comment by zseder** [comment]
since `default_input_scale` was set to `2.0`, projection layer caused this error, because indexing got messed up. For ProjectionLayer, we should use input_scale less than or equal to 1.0

**Comment by zseder** [comment]
fixed in https://github.com/zseder/hunvec/commit/9aed111a6793b5c6f2973e2ec73c13339918b870
