### ISSUE TITLE
tagger.py bug

### ISSUE THREAD

**Issue by pajkossy** [zseder/hunvec#63]
Traceback (most recent call last):
  File "hunvec/seqtag/tagger.py", line 61, in <module>
    main()
  File "hunvec/seqtag/tagger.py", line 57, in main
    tag(args)
  File "hunvec/seqtag/tagger.py", line 48, in tag
    tags = wt.tag_sen(words, feats)
  File "/home/pajkossy/hunvec/hunvec/seqtag/sequence_tagger.py", line 224, in tag_sen
    y = self.f(words, feats)
  File "/home/pajkossy/pylearn_env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 608, in __call__
    storage_map=self.fn.storage_map)
  File "/home/pajkossy/pylearn_env/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 597, in __call__
    outputs = self.fn()
IndexError: index 30 is out of bounds for size 28
Apply node that caused the error: AdvancedSubtensor1(feats_W, Flatten{1}.0)
Inputs types: [TensorType(float64, matrix), TensorType(int64, vector)]
Inputs shapes: [(28, 5), (52,)]
Inputs strides: [(40, 8), (8,)]
Inputs values: ['not shown', 'not shown']

**Comment by zseder** [comment]
hopefully fixed in #64, please test it.
warning: datasets and models has to be retrained, old models won't work (without manual modification)

**Comment by pajkossy** [comment]
fixed
